using System;
using System.Collections.Generic;

/// <summary>What is known about a source, for display: filled
/// from the URL for a plain open and from the resolver's answer for a page
/// URL, with whatever <see cref="BasisMediaPlayer.ApplyMetadata"/> added.
/// Served as a copy by <see cref="BasisMediaPlayer.Metadata"/>.</summary>
public sealed class BasisMediaMetadata
{
    public string SourceUrl;
    public string FileName;
    public string Title;
    public string Uploader;
    public string ThumbnailUrl;
    public TimeSpan? Duration;
    public List<BasisSubtitleTrack> SubtitleTracks;
    public string Provider;

    const int MaxExtensionLength = 5;

    /// <summary>A title from the URL's last path segment, the file name when
    /// it carries a short extension, else the host.</summary>
    public static BasisMediaMetadata FromUrl(string url)
    {
        var meta = new BasisMediaMetadata { SourceUrl = url, Provider = "url" };
        string last = null, host = null;
        if (Uri.TryCreate(url, UriKind.Absolute, out Uri parsed))
        {
            host = parsed.Host;
            string path = parsed.AbsolutePath;
            int slash = path.LastIndexOf('/');
            last = slash >= 0 ? path.Substring(slash + 1) : path;
            try { last = Uri.UnescapeDataString(last); }
            catch (UriFormatException) { }
        }
        if (!string.IsNullOrEmpty(last))
        {
            int dot = last.LastIndexOf('.');
            if (dot > 0 && dot < last.Length - 1 && last.Length - dot - 1 <= MaxExtensionLength)
            {
                meta.FileName = last;
                meta.Title = last.Substring(0, dot);
            }
            else
            {
                meta.Title = last;
            }
        }
        if (string.IsNullOrEmpty(meta.Title))
            meta.Title = !string.IsNullOrEmpty(host) ? host : (url ?? string.Empty);
        return meta;
    }

    public static BasisMediaMetadata FromResolved(BasisResolvedMedia media)
    {
        if (media == null) return null;
        return new BasisMediaMetadata
        {
            SourceUrl = media.SourceUrl,
            Title = media.Title,
            Uploader = media.Uploader,
            ThumbnailUrl = media.ThumbnailUrl,
            Duration = media.Duration.HasValue && media.Duration.Value > TimeSpan.Zero ? media.Duration : null,
            SubtitleTracks = CopyTracks(media.SubtitleTracks),
            Provider = media.Provider,
        };
    }

    public BasisMediaMetadata Clone()
    {
        var copy = (BasisMediaMetadata)MemberwiseClone();
        copy.SubtitleTracks = CopyTracks(SubtitleTracks);
        return copy;
    }

    /// <summary>Take every field <paramref name="other"/> has set.</summary>
    public void MergeFrom(BasisMediaMetadata other)
    {
        if (other == null) return;
        if (!string.IsNullOrEmpty(other.SourceUrl)) SourceUrl = other.SourceUrl;
        if (!string.IsNullOrEmpty(other.FileName)) FileName = other.FileName;
        if (!string.IsNullOrEmpty(other.Title)) Title = other.Title;
        if (!string.IsNullOrEmpty(other.Uploader)) Uploader = other.Uploader;
        if (!string.IsNullOrEmpty(other.ThumbnailUrl)) ThumbnailUrl = other.ThumbnailUrl;
        if (other.Duration.HasValue) Duration = other.Duration;
        if (other.SubtitleTracks != null && other.SubtitleTracks.Count > 0) SubtitleTracks = CopyTracks(other.SubtitleTracks);
        if (!string.IsNullOrEmpty(other.Provider)) Provider = other.Provider;
    }

    static List<BasisSubtitleTrack> CopyTracks(IReadOnlyList<BasisSubtitleTrack> tracks)
    {
        if (tracks == null) return null;
        var copy = new List<BasisSubtitleTrack>(tracks.Count);
        for (int i = 0; i < tracks.Count; i++)
        {
            BasisSubtitleTrack track = tracks[i];
            if (track == null) continue;
            copy.Add(new BasisSubtitleTrack
            {
                Url = track.Url,
                Format = track.Format,
                Language = track.Language,
                Label = track.Label,
                IsAutoGenerated = track.IsAutoGenerated,
            });
        }
        return copy;
    }
}
