using System.Reflection;
using UnityEditor.Rendering.Universal.ShaderGraph;
using UnityEditor.ShaderGraph;
using UnityEngine;

namespace UnityEditor.Rendering.Universal.ShaderGraph
{
    /// <summary>
    /// The light a 2D shadow is being drawn for, in the space the projection runs in.
    ///
    /// Scoped to the ShadowCaster2D SubTarget: it calls <c>SoftShadowLightPosition()</c> and reads
    /// <c>_ShadowRadius</c>, neither of which exists in any other generated shader. Without the filter
    /// the node would be droppable into a Lit graph and fail to compile there.
    ///
    /// <c>Position</c> is the light's WORLD position, all three components, straight from
    /// <c>_LightPos</c> (which ShadowRendering sets from <c>light.transform.position</c>).
    ///
    /// Three components on purpose, and world so that it pairs with Position (World) without the author
    /// having to know which space the projection runs in.
    ///
    /// DO NOT build a fake-3D shadow length out of this. The obvious construction -- difference this
    /// against Position (World), split off a world axis as "height", take the rest as planar distance,
    /// similar triangles -- hard-codes the world axes as the game's frame, and is wrong the moment
    /// anything is rotated out of them. Rotating an entire scene as a rigid body then changes the
    /// shadows, which is not a visible change and should not produce one. Do that arithmetic against
    /// the caster's own plane instead: <c>SoftShadowLightLocal</c> and <c>SoftShadowPointToLocal</c>
    /// are declared pre-graph by ShadowCaster2DGlobals.hlsl, so a Custom Function node can call them
    /// and reach the light and the point in a frame with no world axis named anywhere.
    ///
    /// Nor can this be fed to Shadow Displacement directly: that port is read in the CASTER'S frame, so
    /// a world vector derived from this node needs a Transform (World -> Object) first. A projection
    /// built on those two helpers stays in the caster's frame throughout and needs no conversion.
    ///
    /// What it is still good for is anything that wants the light itself rather than a projection: the
    /// distance to it, a falloff, a flicker keyed to which light is drawing.
    /// </summary>
    [Title("Input", "2D", "Active Shadow2D Light")]
    [SubTargetFilterAttribute(new[] { typeof(UniversalShadowCaster2DSubTarget) })]
    class ShadowCaster2DLightNode : CodeFunctionNode
    {
        public ShadowCaster2DLightNode()
        {
            name = "Active Shadow2D Light";
            synonyms = new[] { "light 2d shadow", "shadow light", "casting light", "light position" };
        }

        // Pure function of uniforms, so it is safe in the Shadow Distance chain -- which is evaluated
        // five times per vertex and requires every input to depend on nothing but the point and
        // uniforms.
        public override bool hasPreview => false;

        protected override MethodInfo GetFunctionToConvert()
            => GetType().GetMethod(nameof(Unity_ShadowCaster2DLight),
                                   BindingFlags.Static | BindingFlags.NonPublic);

        static string Unity_ShadowCaster2DLight(
            [Slot(0, Binding.None)] out Vector3 Position,
            [Slot(1, Binding.None)] out Vector1 Radius)
        {
            // Vector1 is an empty marker struct, so definite assignment is vacuous and the house style
            // leaves it alone; Vector3 has fields and does need one.
            Position = Vector3.zero;
            return
@"
{
    #if SHADERGRAPH_PREVIEW
    // Node and master previews are generated by PreviewTarget, which carries none of this SubTarget's
    // pregraph declarations -- so _LightPos and _ShadowRadius do not exist there. Without this branch
    // any node DOWNSTREAM of this one fails its own preview with 'undeclared identifier _LightPos',
    // because that preview compiles this function too. Stand-in values, chosen only to be plausible.
    Position = half3(0, 3, 0);
    Radius = 10;
    #else
    Position = _LightPos;
    Radius = _ShadowRadius;
    #endif
}
";
        }
    }
}
