// An out-of-band subtitle/caption track the player can fetch and render
// through the caption overlay. Populated by resolvers (or any enrichment
// source) through BasisMediaPlayer.SetSubtitleTracks; the media itself may
// carry none. Format names the payload syntax ("json3") so parser dispatch
// can grow more formats without model changes.
public sealed class BasisSubtitleTrack
{
    public string Url;

    public string Format;

    public string Language;

    public string Label;

    public bool IsAutoGenerated;
}
